spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  datasource:
    username: gfadmin
    password: gameyfin
    db-name: gameyfin_db
    url: jdbc:h2:file:${gameyfin.db}/${spring.datasource.db-name}
    driverClassName: org.h2.Driver