gameyfin:
  db: ""
  cache: ""
  file-extensions: iso, zip, rar, 7z, exe
  file-suffixes: windows, win, english, win32, win64, opengl, stable
  igdb:
    api:
      client-id:
      client-secret:
      max-concurrent-requests: 2
      max-requests-per-second: 4
    config:
      preferred-platforms: 6
