server:
  error.include-stacktrace: never

spring:
  mvc:
    async.request-timeout: -1
  jackson.default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        event.merge.entity_copy_observer: allow