server.port: 8080
spring.jackson.default-property-inclusion: non_null

gameyfin:
  root: ""
  file-extensions: iso, zip, rar, 7z, exe
  igdb:
    config:
      preferred-platform: 6
    api:
      client-id: ""
      client-secret: ""