server:
  port: 8080
  error.include-stacktrace: never

spring:
  jackson.default-property-inclusion: non_null
  datasource.db-name: gameyfin_db
  datasource.url: jdbc:h2:file:./data/${spring.datasource.db-name};AUTO_SERVER=TRUE
  datasource.username: gfadmin
  datasource.password: gameyfin
  datasource.driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        event.merge.entity_copy_observer: allow

gameyfin:
  root: ""
  file-extensions: iso, zip, rar, 7z, exe
  igdb:
    config:
      preferred-platforms: 6
    api:
      client-id: ""
      client-secret: ""