server:
  port: 8080

spring:
  datasource.db-name: gameyfin_db
  datasource.url: jdbc:h2:file:${gameyfin.db}/${spring.datasource.db-name};AUTO_SERVER=TRUE
  datasource.username: gfadmin
  datasource.password: gameyfin
  datasource.driverClassName: org.h2.Driver

gameyfin:
  user: ""
  password: ""
  root: ""
  cache: ${gameyfin.root}\.gameyfin\cache
  db: ${gameyfin.root}\.gameyfin\db # Currently unused
  file-extensions: iso, zip, rar, 7z, exe
  igdb:
    config:
      preferred-platforms: 6
    api:
      client-id: ""
      client-secret: ""