gameyfin:
  user: admin
  password: password
  cache: ${gameyfin.root}\.gameyfin\cache
  db: ${gameyfin.root}\.gameyfin\db

logging:
  level:
    de.grimsi: debug
    # org.springframework.web.reactive.function.client.ExchangeFunctions: debug

spring.mvc.log-request-details: true